### ISSUE TITLE
Weapons don't hide when they're supposed too

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#103]
**Describe the bug**
Weapons stay visible 100% of the time during battle, I think related to the same attaching to node bug mentioned here https://github.com/Pherakki/BlenderToolsForGFS/issues/98

**To Reproduce**
1. Import any weapon model
2. Export weapon model
3. Go into battle

**Expected behavior**
The weapon should hide when necessary during battle. 

**Files**
Model/Weapon/(any gmd)

**Comment by Pherakki** [comment]
Fixed in fde74c13b4db0cc5a801e547b9b7b703482e0440
