### ISSUE TITLE
A mesh with multiple materials will only export primary (first) material

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#104]
**Describe the bug**
If you have a mesh with multiple materials, instead of raising an error or splitting the mesh by materials, it will just export the mesh and assign the entire thing to the first material in the list. This will cause some obvious issues as the whole mesh might not really use 

**To Reproduce**
1. Grab a mesh and make it use multiple mats, for instance combining some meshes in a p5r model
2. Export
3. See how it looks in game

**Expected behavior**
Ideally it should split the mesh from mats by import, either automatically or with a checkbox. Example of script usage is here https://github.com/MadMax1960/NaoTools/blob/main/naotools/__init__.py

**Files**
Any file

**Comment by Pherakki** [comment]
Implemented in 19dbe2275516728b3d235fdbb5642f4f7cb9d443
