### ISSUE TITLE
Various NaoTools features 

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#106]
**Provide details on the proposal.**
In NaoTools https://github.com/MadMax1960/NaoTools/blob/main/naotools/__init__.py various parts of importing into p5r are automated in a sense. The plugin currently has errors for some of these like more than 4 weight groups in a vertex, or a mesh isn't triangulated. However maybe you could use the script to instead just have the plugin fix these issues for the user on export? An especially useful one would be the uv renaming feature, maybe automatically exporting based on whatever uv the material needs?

**Comment by Pherakki** [comment]
Auto-split by mesh implemented here 19dbe2275516728b3d235fdbb5642f4f7cb9d443
Auto-triangulation implemented here 93fd8ed7dafb534829a9f15f595ab4d91d2e86fc
Auto-vertex-group-stripping implemented here 461958c29180c8becf151042cde4f253d2bb89f7
Will review this issue as part of v0.2 with respect to UV map export

**Comment by Pherakki** [comment]
UV map renaming implemented in 0171bdaa06c5388203f705affb443e319da9d055 and a53a724c62a346202956fe2665c5086799cfa4e3
