### ISSUE TITLE
P4D Raw Import --> Export makes vertex colors die(?)

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#126]
**Describe the bug**
When doing a raw import --> export of a p4d model, the model becomes solid color. This usually happens when vertex colors just kinda die, but it could also be mat related? It's solved by manually editing random stuff in gfd until it works. 

**To Reproduce**
1. Open P4D Model
2. Export P4D Model
3. Look at in gfd or 010 and see what changed ig? 
4. Or boot up game with vita3k

**Expected behavior**
It should just export the model normally

**Files**
If you don't have a p4d dump, heres an example model https://cdn.discordapp.com/attachments/831687902824103977/1156280346183225414/pc007_23.GMD?ex=6514657d&is=651313fd&hm=cab85d9cd339e38b2025b26e5f1df40278a274a44df07c3fa7cd3edd2dbc4432&

**Additional context**

**Comment by Pherakki** [comment]
Fixed in 5f5d4f09a5d03bef3f5d2a0ae467e448e0fe7c10
