### ISSUE TITLE
Animation Export Error: Animation Interface has no attribute "Bones"

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#127]
**Describe the bug**
Bug seems to happen when adding a new bone to a skeleton with a gap put on armature. 

**To Reproduce**
1. Import model
2. Import gap on model
3. Add new bone
4. Animate bone
5. Try to export gap or model with anims packed

**Expected behavior**
It should work with new bones just fine, and export correctly. 

**Files**
Here's example blend. With 2 bones added to Bip01 Head. https://cdn.discordapp.com/attachments/831687902824103977/1156281310164291584/gojo_69.blend?ex=65146663&is=651314e3&hm=0815b33321c1f367d95b966c09c22aedd1df963ff0f414f54aa8e6c32b8184d8&

**Comment by Pherakki** [comment]
Fixed in a7ba1ddfc2da8b83013772a0fae513b2ec0bc9e0
