### ISSUE TITLE
2 Uv Spheres Fail to Export

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#91]
**Describe the bug**
2 Uv Spheres with same mat setup fail to export

**To Reproduce**
Try to export

**Expected behavior**
It should Export

**Files**
https://cdn.discordapp.com/attachments/473675595088134159/1095643986582044752/ballstrue.blend

**Comment by Pherakki** [comment]
Note to self: this is due to the meshes not being parented to the armature, and the plugin raises an unhandled error instead of just not exporting the meshes. Should just need an extra safety check to fix.

**Comment by Pherakki** [comment]
Fixed in 6376073efdb5e148db0c5487966151c5efe5f122
