### ISSUE TITLE
Tutorial about how to create a custom GFS with a 3D model we have

### ISSUE THREAD

**Issue by Lurius-Kitsune** [Pherakki/BlenderToolsForGFS#94]
**Provide details on the proposal.**
I could like to get a tutorial about how to do it, it could be create to convert vrchat avatar to persona5 

**Is your feature request related to a problem? Please describe.**
Nope ! ^^

**Additional context**
Exemple of avatar : 
![Lurius_Beta_Rendu](https://github.com/Pherakki/BlenderToolsForGFS/assets/81522727/c50ee753-b7a3-459a-a07c-f6fc00c884d3)

**Comment by Pherakki** [comment]
The documentation provided alongside the plugin should be able to tell you how to export a 3D model in the GFS format using the plugin. The goal is for the documentation to provide all the information you require to understand how to successfully export from Blender to the GMD/GFS format.

Can you describe what information is missing from the documentation that prevents you from being able to do this?

**Comment by Lurius-Kitsune** [comment]
This model created by rezillio, ihave the weight pain done on more than 4 vertex group, so it does'nt want to go exported

**Comment by Pherakki** [comment]
It sounds to me as though you are having difficulties with model-editing in Blender rather than an issue with the plugin itself?
