### ISSUE TITLE
GAP files do not export with bounding boxes

### ISSUE THREAD

**Issue by WisteriaSp** [Pherakki/BlenderToolsForGFS#95]
**Describe the bug**
GAP files exported with this plugin are stripped of their bounding boxes and cause the animations to be culled out when played in-game.

**To Reproduce**
1. Import a vanilla GAP or any GAP with bounding boxes (check with gfdstudio)
2. Export the GAP
3. Check if the animations have bounding box values in gfd studio

**Expected behavior**
GAP files are exported with the original bounding box values found in the imported GAP.

**Files**
Any GAP file, but I used 0004/Battle/BB0004_051.GAP and 0010/Battle/BB0010_051.GAP as examples.

**Comment by Pherakki** [comment]
Thanks for the report. This has been triaged and I'll try to figure out a solution when I'm able to resume work on v0.1.1.

**Comment by Pherakki** [comment]
Fixed in f4af1420b59136465d069c6b9dc194be4af4b34d
