### ISSUE TITLE
Vertex Colors become full white on export

### ISSUE THREAD

**Issue by DniweTamp** [Pherakki/BlenderToolsForGFS#97]
**Bug description**
Importing models with vertex colors works without issues, they appear correctly in blender, but exporting the same model will turn all vertex colors white

**To Reproduce**
1. Import any GMD/GFS with vertex colors (for example, Futaba Palace entrance GFS, the sand uses vertex colors for shading)
2. Export the model back to GMD
3. Import it again (or check ingame), and vertex colors will be white

**Expected behavior**
Keeping vertex colors on export

**Files**
model\field_tex\F055_010_0.GFS from P5R - sand material

**Comment by Pherakki** [comment]
Note to self: Proably related to BYTE_COLOR vs FLOAT_COLOR enum - c.f. https://github.com/Pherakki/BlenderToolsForGFS/blob/6376073efdb5e148db0c5487966151c5efe5f122/src/BlenderIO/Import/ImportModel.py#L707
Might be fixed by refactoring Blender I/O to use upcoming utils library

**Comment by Pherakki** [comment]
Fixed in b89721687d60135beeb34a9a68bb399eabebd056
