### ISSUE TITLE
Meshes parented to nodes dont properly export 

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#98]
**Describe the bug**
Meshes parented to nodes (Such as some eyes in p5r, or morgana facial meshes in p5d) dont properly export. And as such won't scale with the nodes. 

**To Reproduce**
1. Import Morgana P5D Model
2. Export Morgana P5D Model

**Expected behavior**
Morgana should work fine, with meshes parented to nodes. 

**Files**
File is attached in a zip

**Additional context**
Akechi apparently uses this for his showtime attack where his eyes shrink, so could test with that too.
[pc203_f1.zip](https://github.com/Pherakki/BlenderToolsForGFS/files/12336547/pc203_f1.zip)

**Comment by Pherakki** [comment]
Pushing to v0.2 since this may require a rework of how meshes are imported/exported

**Comment by Pherakki** [comment]
Fixed in commit hell around 1f64a174de1fa6535094fd49c52b21cbafd13f3e
