### ISSUE TITLE
GAP export fails to calculate length of animation

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#99]
**Describe the bug**
When exporting some gaps, they will export with length set to 0 so you have to manually calculate and input in 010 or gfd. 

**To Reproduce**
1. Open GMD
2. Export Gap or with Gap embedded in GMD 
3. Look at length

**Expected behavior**
Gap is exported with no issues and calculates length on export

**Files**
GMD attached

[bc003.zip](https://github.com/Pherakki/BlenderToolsForGFS/files/12336580/bc003.zip)

**Comment by Pherakki** [comment]
Fixed in 7b7edec63f90febf0dd1cb9042b3c146cae88a95.
I should note that *every* animation prior to this commit will have exported with a shorter (or equal) duration than the correct one.
